# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clusterstate_pb2 as clusterstate__pb2


class ClusterStateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateClusterState = channel.unary_unary(
                '/controller.ClusterStateService/UpdateClusterState',
                request_serializer=clusterstate__pb2.UpdateClusterStateRequest.SerializeToString,
                response_deserializer=clusterstate__pb2.UpdateClusterStateResponse.FromString,
                )


class ClusterStateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateClusterState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateClusterState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClusterState,
                    request_deserializer=clusterstate__pb2.UpdateClusterStateRequest.FromString,
                    response_serializer=clusterstate__pb2.UpdateClusterStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.ClusterStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClusterStateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateClusterState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.ClusterStateService/UpdateClusterState',
            clusterstate__pb2.UpdateClusterStateRequest.SerializeToString,
            clusterstate__pb2.UpdateClusterStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
