# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clusterstate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63lusterstate.proto\x12\ncontroller\x1a\x1egoogle/protobuf/wrappers.proto\"\xd1\x01\n\x13InvokerClusterState\x12Y\n\x15\x61\x63tionStatePerInvoker\x18\x01 \x03(\x0b\x32:.controller.InvokerClusterState.ActionStatePerInvokerEntry\x1a_\n\x1a\x41\x63tionStatePerInvokerEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.controller.ActionStatePerInvoker:\x02\x38\x01\"\xc6\x01\n\x15\x41\x63tionStatePerInvoker\x12I\n\x0c\x61\x63tionStates\x18\x01 \x03(\x0b\x32\x33.controller.ActionStatePerInvoker.ActionStatesEntry\x12\x14\n\x0c\x66reeMemoryMB\x18\x02 \x01(\x03\x1aL\n\x11\x41\x63tionStatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.controller.ActionState:\x02\x38\x01\"\x98\x01\n\x0b\x41\x63tionState\x12;\n\nstateLists\x18\x01 \x03(\x0b\x32\'.controller.ActionState.StateListsEntry\x1aL\n\x0fStateListsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.controller.ContainerList:\x02\x38\x01\"=\n\rContainerList\x12,\n\ncontainers\x18\x01 \x03(\x0b\x32\x18.controller.RPCContainer\",\n\x0cRPCContainer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63ore_pin\x18\x02 \x01(\t\"R\n\x19UpdateClusterStateRequest\x12\x35\n\x0c\x63lusterState\x18\x01 \x01(\x0b\x32\x1f.controller.InvokerClusterState\"\x1c\n\x1aUpdateClusterStateResponse2|\n\x13\x43lusterStateService\x12\x65\n\x12UpdateClusterState\x12%.controller.UpdateClusterStateRequest\x1a&.controller.UpdateClusterStateResponse\"\x00\x42\x30\n\x19org.apache.openwhisk.grpcB\x11\x43lusterStateProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clusterstate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031org.apache.openwhisk.grpcB\021ClusterStateProtoP\001'
  _INVOKERCLUSTERSTATE_ACTIONSTATEPERINVOKERENTRY._options = None
  _INVOKERCLUSTERSTATE_ACTIONSTATEPERINVOKERENTRY._serialized_options = b'8\001'
  _ACTIONSTATEPERINVOKER_ACTIONSTATESENTRY._options = None
  _ACTIONSTATEPERINVOKER_ACTIONSTATESENTRY._serialized_options = b'8\001'
  _ACTIONSTATE_STATELISTSENTRY._options = None
  _ACTIONSTATE_STATELISTSENTRY._serialized_options = b'8\001'
  _globals['_INVOKERCLUSTERSTATE']._serialized_start=67
  _globals['_INVOKERCLUSTERSTATE']._serialized_end=276
  _globals['_INVOKERCLUSTERSTATE_ACTIONSTATEPERINVOKERENTRY']._serialized_start=181
  _globals['_INVOKERCLUSTERSTATE_ACTIONSTATEPERINVOKERENTRY']._serialized_end=276
  _globals['_ACTIONSTATEPERINVOKER']._serialized_start=279
  _globals['_ACTIONSTATEPERINVOKER']._serialized_end=477
  _globals['_ACTIONSTATEPERINVOKER_ACTIONSTATESENTRY']._serialized_start=401
  _globals['_ACTIONSTATEPERINVOKER_ACTIONSTATESENTRY']._serialized_end=477
  _globals['_ACTIONSTATE']._serialized_start=480
  _globals['_ACTIONSTATE']._serialized_end=632
  _globals['_ACTIONSTATE_STATELISTSENTRY']._serialized_start=556
  _globals['_ACTIONSTATE_STATELISTSENTRY']._serialized_end=632
  _globals['_CONTAINERLIST']._serialized_start=634
  _globals['_CONTAINERLIST']._serialized_end=695
  _globals['_RPCCONTAINER']._serialized_start=697
  _globals['_RPCCONTAINER']._serialized_end=741
  _globals['_UPDATECLUSTERSTATEREQUEST']._serialized_start=743
  _globals['_UPDATECLUSTERSTATEREQUEST']._serialized_end=825
  _globals['_UPDATECLUSTERSTATERESPONSE']._serialized_start=827
  _globals['_UPDATECLUSTERSTATERESPONSE']._serialized_end=855
  _globals['_CLUSTERSTATESERVICE']._serialized_start=857
  _globals['_CLUSTERSTATESERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
