# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\ncontroller\x1a\x1egoogle/protobuf/wrappers.proto\"/\n\x19GetInvocationRouteRequest\x12\x12\n\nactionName\x18\x01 \x01(\t\"1\n\x1aGetInvocationRouteResponse\x12\x13\n\x0binvokerHost\x18\x01 \x01(\t\"\xd3\x01\n\x14InvokerStateByAction\x12X\n\x14invokerStateByAction\x18\x01 \x03(\x0b\x32:.controller.InvokerStateByAction.InvokerStateByActionEntry\x1a\x61\n\x19InvokerStateByActionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.controller.ContainerStatesByInvoker:\x02\x38\x01\"\xe3\x01\n\x18\x43ontainerStatesByInvoker\x12\x64\n\x18\x63ontainerStatesByInvoker\x18\x01 \x03(\x0b\x32\x42.controller.ContainerStatesByInvoker.ContainerStatesByInvokerEntry\x1a\x61\n\x1d\x43ontainerStatesByInvokerEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .controller.ContainerStateCounts:\x02\x38\x01\"\x92\x01\n\x14\x43ontainerStateCounts\x12\x46\n\x0bstateCounts\x18\x01 \x03(\x0b\x32\x31.controller.ContainerStateCounts.StateCountsEntry\x1a\x32\n\x10StateCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"]\n\x0c\x43lusterState\x12\x1b\n\x13healthyInvokerCount\x18\x01 \x01(\r\x12\x30\n\x06states\x18\x02 \x01(\x0b\x32 .controller.InvokerStateByAction\"K\n\x19UpdateClusterStateRequest\x12.\n\x0c\x63lusterState\x18\x01 \x01(\x0b\x32\x18.controller.ClusterState\"\x1c\n\x1aUpdateClusterStateResponse2\xe1\x01\n\x11\x43ontrollerService\x12\x65\n\x12GetInvocationRoute\x12%.controller.GetInvocationRouteRequest\x1a&.controller.GetInvocationRouteResponse\"\x00\x12\x65\n\x12UpdateClusterState\x12%.controller.UpdateClusterStateRequest\x1a&.controller.UpdateClusterStateResponse\"\x00\x42.\n\x19org.apache.openwhisk.grpcB\x0f\x43ontrollerProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031org.apache.openwhisk.grpcB\017ControllerProtoP\001'
  _INVOKERSTATEBYACTION_INVOKERSTATEBYACTIONENTRY._options = None
  _INVOKERSTATEBYACTION_INVOKERSTATEBYACTIONENTRY._serialized_options = b'8\001'
  _CONTAINERSTATESBYINVOKER_CONTAINERSTATESBYINVOKERENTRY._options = None
  _CONTAINERSTATESBYINVOKER_CONTAINERSTATESBYINVOKERENTRY._serialized_options = b'8\001'
  _CONTAINERSTATECOUNTS_STATECOUNTSENTRY._options = None
  _CONTAINERSTATECOUNTS_STATECOUNTSENTRY._serialized_options = b'8\001'
  _globals['_GETINVOCATIONROUTEREQUEST']._serialized_start=64
  _globals['_GETINVOCATIONROUTEREQUEST']._serialized_end=111
  _globals['_GETINVOCATIONROUTERESPONSE']._serialized_start=113
  _globals['_GETINVOCATIONROUTERESPONSE']._serialized_end=162
  _globals['_INVOKERSTATEBYACTION']._serialized_start=165
  _globals['_INVOKERSTATEBYACTION']._serialized_end=376
  _globals['_INVOKERSTATEBYACTION_INVOKERSTATEBYACTIONENTRY']._serialized_start=279
  _globals['_INVOKERSTATEBYACTION_INVOKERSTATEBYACTIONENTRY']._serialized_end=376
  _globals['_CONTAINERSTATESBYINVOKER']._serialized_start=379
  _globals['_CONTAINERSTATESBYINVOKER']._serialized_end=606
  _globals['_CONTAINERSTATESBYINVOKER_CONTAINERSTATESBYINVOKERENTRY']._serialized_start=509
  _globals['_CONTAINERSTATESBYINVOKER_CONTAINERSTATESBYINVOKERENTRY']._serialized_end=606
  _globals['_CONTAINERSTATECOUNTS']._serialized_start=609
  _globals['_CONTAINERSTATECOUNTS']._serialized_end=755
  _globals['_CONTAINERSTATECOUNTS_STATECOUNTSENTRY']._serialized_start=705
  _globals['_CONTAINERSTATECOUNTS_STATECOUNTSENTRY']._serialized_end=755
  _globals['_CLUSTERSTATE']._serialized_start=757
  _globals['_CLUSTERSTATE']._serialized_end=850
  _globals['_UPDATECLUSTERSTATEREQUEST']._serialized_start=852
  _globals['_UPDATECLUSTERSTATEREQUEST']._serialized_end=927
  _globals['_UPDATECLUSTERSTATERESPONSE']._serialized_start=929
  _globals['_UPDATECLUSTERSTATERESPONSE']._serialized_end=957
  _globals['_CONTROLLERSERVICE']._serialized_start=960
  _globals['_CONTROLLERSERVICE']._serialized_end=1185
# @@protoc_insertion_point(module_scope)
