# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import controller_pb2 as controller__pb2


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInvocationRoute = channel.unary_unary(
                '/controller.ControllerService/GetInvocationRoute',
                request_serializer=controller__pb2.GetInvocationRouteRequest.SerializeToString,
                response_deserializer=controller__pb2.GetInvocationRouteResponse.FromString,
                )
        self.UpdateClusterState = channel.unary_unary(
                '/controller.ControllerService/UpdateClusterState',
                request_serializer=controller__pb2.UpdateClusterStateRequest.SerializeToString,
                response_deserializer=controller__pb2.UpdateClusterStateResponse.FromString,
                )


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInvocationRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClusterState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInvocationRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvocationRoute,
                    request_deserializer=controller__pb2.GetInvocationRouteRequest.FromString,
                    response_serializer=controller__pb2.GetInvocationRouteResponse.SerializeToString,
            ),
            'UpdateClusterState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClusterState,
                    request_deserializer=controller__pb2.UpdateClusterStateRequest.FromString,
                    response_serializer=controller__pb2.UpdateClusterStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInvocationRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.ControllerService/GetInvocationRoute',
            controller__pb2.GetInvocationRouteRequest.SerializeToString,
            controller__pb2.GetInvocationRouteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateClusterState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.ControllerService/UpdateClusterState',
            controller__pb2.UpdateClusterStateRequest.SerializeToString,
            controller__pb2.UpdateClusterStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
