# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clusterstate_pb2 as clusterstate__pb2
import routing_pb2 as routing__pb2


class RoutingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInvocationRoute = channel.unary_unary(
                '/controller.RoutingService/GetInvocationRoute',
                request_serializer=routing__pb2.GetInvocationRouteRequest.SerializeToString,
                response_deserializer=routing__pb2.GetInvocationRouteResponse.FromString,
                )
        self.RoutingUpdateClusterState = channel.unary_unary(
                '/controller.RoutingService/RoutingUpdateClusterState',
                request_serializer=clusterstate__pb2.UpdateClusterStateRequest.SerializeToString,
                response_deserializer=clusterstate__pb2.UpdateClusterStateResponse.FromString,
                )
        self.GetArrivalInfo = channel.unary_unary(
                '/controller.RoutingService/GetArrivalInfo',
                request_serializer=routing__pb2.EmptyRequest.SerializeToString,
                response_deserializer=routing__pb2.GetArrivalInfoResponse.FromString,
                )


class RoutingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInvocationRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RoutingUpdateClusterState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArrivalInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInvocationRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvocationRoute,
                    request_deserializer=routing__pb2.GetInvocationRouteRequest.FromString,
                    response_serializer=routing__pb2.GetInvocationRouteResponse.SerializeToString,
            ),
            'RoutingUpdateClusterState': grpc.unary_unary_rpc_method_handler(
                    servicer.RoutingUpdateClusterState,
                    request_deserializer=clusterstate__pb2.UpdateClusterStateRequest.FromString,
                    response_serializer=clusterstate__pb2.UpdateClusterStateResponse.SerializeToString,
            ),
            'GetArrivalInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArrivalInfo,
                    request_deserializer=routing__pb2.EmptyRequest.FromString,
                    response_serializer=routing__pb2.GetArrivalInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.RoutingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RoutingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInvocationRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.RoutingService/GetInvocationRoute',
            routing__pb2.GetInvocationRouteRequest.SerializeToString,
            routing__pb2.GetInvocationRouteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RoutingUpdateClusterState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.RoutingService/RoutingUpdateClusterState',
            clusterstate__pb2.UpdateClusterStateRequest.SerializeToString,
            clusterstate__pb2.UpdateClusterStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArrivalInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.RoutingService/GetArrivalInfo',
            routing__pb2.EmptyRequest.SerializeToString,
            routing__pb2.GetArrivalInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
