# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import clusterstate_pb2 as clusterstate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrouting.proto\x12\ncontroller\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x12\x63lusterstate.proto\"\x0e\n\x0c\x45mptyRequest\"\x9e\x02\n\x16GetArrivalInfoResponse\x12L\n\x0equery_count_1s\x18\x01 \x03(\x0b\x32\x34.controller.GetArrivalInfoResponse.QueryCount1sEntry\x12L\n\x0equery_count_5s\x18\x02 \x03(\x0b\x32\x34.controller.GetArrivalInfoResponse.QueryCount5sEntry\x1a\x33\n\x11QueryCount1sEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x33\n\x11QueryCount5sEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"/\n\x19GetInvocationRouteRequest\x12\x12\n\nactionName\x18\x01 \x01(\t\"7\n\x1aGetInvocationRouteResponse\x12\x19\n\x11invokerInstanceId\x18\x01 \x01(\x05\x32\xb7\x02\n\x0eRoutingService\x12\x65\n\x12GetInvocationRoute\x12%.controller.GetInvocationRouteRequest\x1a&.controller.GetInvocationRouteResponse\"\x00\x12l\n\x19RoutingUpdateClusterState\x12%.controller.UpdateClusterStateRequest\x1a&.controller.UpdateClusterStateResponse\"\x00\x12P\n\x0eGetArrivalInfo\x12\x18.controller.EmptyRequest\x1a\".controller.GetArrivalInfoResponse\"\x00\x42+\n\x19org.apache.openwhisk.grpcB\x0cRoutingProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031org.apache.openwhisk.grpcB\014RoutingProtoP\001'
  _GETARRIVALINFORESPONSE_QUERYCOUNT1SENTRY._options = None
  _GETARRIVALINFORESPONSE_QUERYCOUNT1SENTRY._serialized_options = b'8\001'
  _GETARRIVALINFORESPONSE_QUERYCOUNT5SENTRY._options = None
  _GETARRIVALINFORESPONSE_QUERYCOUNT5SENTRY._serialized_options = b'8\001'
  _globals['_EMPTYREQUEST']._serialized_start=81
  _globals['_EMPTYREQUEST']._serialized_end=95
  _globals['_GETARRIVALINFORESPONSE']._serialized_start=98
  _globals['_GETARRIVALINFORESPONSE']._serialized_end=384
  _globals['_GETARRIVALINFORESPONSE_QUERYCOUNT1SENTRY']._serialized_start=280
  _globals['_GETARRIVALINFORESPONSE_QUERYCOUNT1SENTRY']._serialized_end=331
  _globals['_GETARRIVALINFORESPONSE_QUERYCOUNT5SENTRY']._serialized_start=333
  _globals['_GETARRIVALINFORESPONSE_QUERYCOUNT5SENTRY']._serialized_end=384
  _globals['_GETINVOCATIONROUTEREQUEST']._serialized_start=386
  _globals['_GETINVOCATIONROUTEREQUEST']._serialized_end=433
  _globals['_GETINVOCATIONROUTERESPONSE']._serialized_start=435
  _globals['_GETINVOCATIONROUTERESPONSE']._serialized_end=490
  _globals['_ROUTINGSERVICE']._serialized_start=493
  _globals['_ROUTINGSERVICE']._serialized_end=804
# @@protoc_insertion_point(module_scope)
