- hosts: localhost
  tasks:
  - name: gen hosts if 'local' env is used
    local_action: template src="{{playbook_dir}}/environments/local/hosts.j2.ini" dest="{{ playbook_dir }}/environments/local/hosts"
    when: "'environments/local' in hosts_dir"