# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import invoker_pb2 as invoker__pb2


class InvokerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewWarmedContainer = channel.unary_unary(
                '/invoker.InvokerService/NewWarmedContainer',
                request_serializer=invoker__pb2.NewWarmedContainerRequest.SerializeToString,
                response_deserializer=invoker__pb2.NewWarmedContainerResponse.FromString,
                )
        self.DeleteContainer = channel.unary_unary(
                '/invoker.InvokerService/DeleteContainer',
                request_serializer=invoker__pb2.DeleteContainerRequest.SerializeToString,
                response_deserializer=invoker__pb2.DeleteContainerResponse.FromString,
                )
        self.SetAllowOpenWhiskToFreeMemory = channel.unary_unary(
                '/invoker.InvokerService/SetAllowOpenWhiskToFreeMemory',
                request_serializer=invoker__pb2.SetAllowOpenWhiskToFreeMemoryRequest.SerializeToString,
                response_deserializer=invoker__pb2.SetAllowOpenWhiskToFreeMemoryResponse.FromString,
                )


class InvokerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewWarmedContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAllowOpenWhiskToFreeMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewWarmedContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.NewWarmedContainer,
                    request_deserializer=invoker__pb2.NewWarmedContainerRequest.FromString,
                    response_serializer=invoker__pb2.NewWarmedContainerResponse.SerializeToString,
            ),
            'DeleteContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteContainer,
                    request_deserializer=invoker__pb2.DeleteContainerRequest.FromString,
                    response_serializer=invoker__pb2.DeleteContainerResponse.SerializeToString,
            ),
            'SetAllowOpenWhiskToFreeMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAllowOpenWhiskToFreeMemory,
                    request_deserializer=invoker__pb2.SetAllowOpenWhiskToFreeMemoryRequest.FromString,
                    response_serializer=invoker__pb2.SetAllowOpenWhiskToFreeMemoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'invoker.InvokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InvokerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewWarmedContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/invoker.InvokerService/NewWarmedContainer',
            invoker__pb2.NewWarmedContainerRequest.SerializeToString,
            invoker__pb2.NewWarmedContainerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/invoker.InvokerService/DeleteContainer',
            invoker__pb2.DeleteContainerRequest.SerializeToString,
            invoker__pb2.DeleteContainerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAllowOpenWhiskToFreeMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/invoker.InvokerService/SetAllowOpenWhiskToFreeMemory',
            invoker__pb2.SetAllowOpenWhiskToFreeMemoryRequest.SerializeToString,
            invoker__pb2.SetAllowOpenWhiskToFreeMemoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
