# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invoker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinvoker.proto\x12\x07invoker\x1a\x1egoogle/protobuf/wrappers.proto\"\x9e\x01\n\x19NewWarmedContainerRequest\x12\x12\n\nactionName\x18\x01 \x01(\t\x12>\n\x06params\x18\x02 \x03(\x0b\x32..invoker.NewWarmedContainerRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"-\n\x1aNewWarmedContainerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x16\x44\x65leteContainerRequest\x12\x12\n\nactionName\x18\x01 \x01(\t\"*\n\x17\x44\x65leteContainerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"8\n$SetAllowOpenWhiskToFreeMemoryRequest\x12\x10\n\x08setValue\x18\x01 \x01(\x08\"8\n%SetAllowOpenWhiskToFreeMemoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xcc\x02\n\x0eInvokerService\x12_\n\x12NewWarmedContainer\x12\".invoker.NewWarmedContainerRequest\x1a#.invoker.NewWarmedContainerResponse\"\x00\x12V\n\x0f\x44\x65leteContainer\x12\x1f.invoker.DeleteContainerRequest\x1a .invoker.DeleteContainerResponse\"\x00\x12\x80\x01\n\x1dSetAllowOpenWhiskToFreeMemory\x12-.invoker.SetAllowOpenWhiskToFreeMemoryRequest\x1a..invoker.SetAllowOpenWhiskToFreeMemoryResponse\"\x00\x42+\n\x19org.apache.openwhisk.grpcB\x0cInvokerProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031org.apache.openwhisk.grpcB\014InvokerProtoP\001'
  _NEWWARMEDCONTAINERREQUEST_PARAMSENTRY._options = None
  _NEWWARMEDCONTAINERREQUEST_PARAMSENTRY._serialized_options = b'8\001'
  _globals['_NEWWARMEDCONTAINERREQUEST']._serialized_start=59
  _globals['_NEWWARMEDCONTAINERREQUEST']._serialized_end=217
  _globals['_NEWWARMEDCONTAINERREQUEST_PARAMSENTRY']._serialized_start=172
  _globals['_NEWWARMEDCONTAINERREQUEST_PARAMSENTRY']._serialized_end=217
  _globals['_NEWWARMEDCONTAINERRESPONSE']._serialized_start=219
  _globals['_NEWWARMEDCONTAINERRESPONSE']._serialized_end=264
  _globals['_DELETECONTAINERREQUEST']._serialized_start=266
  _globals['_DELETECONTAINERREQUEST']._serialized_end=310
  _globals['_DELETECONTAINERRESPONSE']._serialized_start=312
  _globals['_DELETECONTAINERRESPONSE']._serialized_end=354
  _globals['_SETALLOWOPENWHISKTOFREEMEMORYREQUEST']._serialized_start=356
  _globals['_SETALLOWOPENWHISKTOFREEMEMORYREQUEST']._serialized_end=412
  _globals['_SETALLOWOPENWHISKTOFREEMEMORYRESPONSE']._serialized_start=414
  _globals['_SETALLOWOPENWHISKTOFREEMEMORYRESPONSE']._serialized_end=470
  _globals['_INVOKERSERVICE']._serialized_start=473
  _globals['_INVOKERSERVICE']._serialized_end=805
# @@protoc_insertion_point(module_scope)
